### ISSUE TITLE
Status

### ISSUE THREAD

**Issue by Kingdutch** [Gizra/og#1]
Hi,

Could you add a section to the README or maybe keep this issue updated with what the status is for d8? Can we use it yet? Can we help you out in any way? I looked at the d.o page for og but there's no mention of D8 either.

Regards,

Alexander

**Comment by RoySegall** [comment]
Hi there @Kingdutch it's funny but i didn't got an email about this one. I now created some tags that will direct us better to our final goal - OG for Drupal 8.

I will update the read me file but the main goal here is to reduce the amount of spegety code, sort of, OG has. For example: I wan to reduce by 75% the code amount in og.module. Probably most of them are hooks definition. We can reduce that by using plugins or services. We need to decide about that.

I'll now open issues that will mark as the alpha release blocker. If you ask what is alpha release is the status when people can use OG without the other sub-modules: og_ui, og_access, og_vocab(although it's a contrinb module) etc. etc.

**Comment by frob** [comment]
Has any thought gone into re architecting OG for Drupal 8.

**Comment by RoySegall** [comment]
Yeah, but other projects holding me.

**Comment by MPParsley** [comment]
See #240 for the roadmap.
