### ISSUE TITLE
Paid-access web application for multiple user accounts per organization

### ISSUE THREAD

**Issue by LordPachelbel** [Gizra/og#108]
We're developing a paid-access web application that requires a multiple-user account system. The subscriptions will be handled with Drupal Commerce. The initial user account from an organization will be the "admin" or "owner" of a group of additional user accounts, and the "owner" will be charged a monthly fee based on how many user accounts — including the "owner" — are in the group. The other accounts in the group will not be charged for access.

Here are some use cases. To make them more concrete, pretend this site is meant for lawyers:

<ol>
  <li><strong>A single, independent lawyer</strong> — A lawyer creates a user account. He is automatically made the "admin/owner" of his "law firm," a group of user accounts in which his account is the only member. His credit card is periodically charged for one user account.</li>
  <li><strong>A multiple-partner law firm</strong> — A lawyer, or receptionist, or office manager, etc. from a law firm creates a user account. He is automatically made the "admin/owner" of his "law firm," a group of user accounts in which his account is the only member (so far). He then creates additional user accounts, and they are automatically added to his "law firm" group.* He has admin rights to edit or delete those additional accounts. His credit card is periodically charged based on how many user accounts he has created. If necessary, he can transfer group ownership to another user in the group.</li>
</ol>

\* We're flexible as to how the additional user accounts could be automatically added to the groups:

<ul>
  <li>The group owner could create the accounts himself, and Drupal would send email notifications to those people.</li>
  <li>The group owner could send an email invitation to people, and they would create their own accounts.</li>
</ul>

Either way, they need to automatically become part of the law firm group when they first log in — we'd rather not require them to take an additional step of explicitly accepting an invitation.

So, which of the following modules is the best one for building this sort of thing?

<ul>
  <li><a href="https://www.drupal.org/project/og">Organic Groups</a></li>
  <li><a href="https://www.drupal.org/project/group">Group</a></li>
  <li><a href="https://www.drupal.org/project/subuser">Subuser</a></li>
  <li><a href="https://www.drupal.org/project/membership_entity">Membership Entity</a></li>
  <li><a href="https://www.drupal.org/project/gcc">Groups, Communities and Co</a></li>
  <li>any other module[s] you know about</li>
</ul>

**Comment by amitaibu** [comment]
Even though I'm biased, I'd say each module can probably accomplish this.

OG, the father of all those modules, is often accused for having a bigger learning curve than others. However, I think that one of the most important points is that its API is battle tested. It's serving _lots_ of high profile sites, which means the bugs, scalability issues, performance have been already ironed out.

**Comment by amitaibu** [comment]
Hope it helps :)
