### ISSUE TITLE
Widget to share existing content in group

### ISSUE THREAD

**Issue by subhojit777** [Gizra/og#11]
This is a **Feature request**

There should be some kind of widget that will appear in node pages. The widget will be like a shortcut to post the node in a group. Currently, you have to go to node edit page and select group where you want to post the content.

The widget will only appear if the user is member of some group.

P.S. I liked the drupal issue queue, you can add tags, etc.

**Comment by amitaibu** [comment]
I believe you can use https://www.drupal.org/project/inline_entity_form

Anyway, it won't be part of OG core.

**Comment by subhojit777** [comment]
I wanted users to be able to add groups from node page itself. I am using panel node variant.

You can use [editablefields](https://www.drupal.org/project/editablefields) for this. Just add the og reference field in panel pane, and select formatter as "Editable". I had to patch the module to get it working, see my [comment](https://www.drupal.org/node/1206656#comment-9378559)

@amitaibu I tried to use inline_entity_form module, but it was not working as per my requirement.

Thanks.
