### ISSUE TITLE
How to handle patches on github

### ISSUE THREAD

**Issue by mike-potter** [Gizra/og#118]
Before you close the issue queue on drupal.org, can you explain the workflow when using github when patches needs to be applied to OG via a make file (like from Open Atrium).

I'm a bit concerned with OG abandoning the drupal.org issue queue since that prevents stuff like automatted testing (testbot), makes a different workflow for security issues, and potentially makes it hard to review and reference patches.

Maybe you can show a specific example of how to post a patch here and then how it can be referenced by drush make.  And will the packaging system on drupal.org even allow external patch links in drush make files point to github or will it have whitelisting issues?

Please be sure all of these issues are addressed before closing the d.o issue queue.  Thanks.

**Comment by amitaibu** [comment]
hi @mike-potter!

D.O isn't _totally_ abandoned - but rather I point people to GitHub as it's a nicer place for me to handle PRs.

For security issues, we're still following the convention and use security.drupal.org properly.

As for drush make - for every PR you can add the suffix `.patch` or `.diff` so you can reference it:

https://github.com/Gizra/og/pull/109
https://github.com/Gizra/og/pull/109.patch
https://github.com/Gizra/og/pull/109.diff

**Comment by mike-potter** [comment]
Right, but correct me if I'm wrong:  If I refer to a patch in my drush drupal-org.make like this:

projects[og][patch][109] = https://github.com/Gizra/og/pull/109.patch

for Open Atrium (for example), isn't the drupal.org packaging system going to reject this because it doesn't allow patches from remote sites?  Or will that actually work?

**Comment by amitaibu** [comment]
I actually don't know - didn't know about this patch origin limitation.

**Comment by mike-potter** [comment]
Yep.  Drupal.org uses the "drush verify-makefile" (http://cgit.drupalcode.org/drupalorg_drush/tree/drupalorg_drush.drush.inc) which has:

define('DRUPALORG_DRUSH_ALLOWED_PATCH_URL', '#^https?://(www.)?drupal.org/files#');

So official distros built on drupal.org aren't allowed to reference patches outside of that url pattern.  Similar to restrictions on using libraries that are not white-listed.

Anyway, as long as you keep the d.o issue queue open for stuff like that, I'm fine.

**Comment by amitaibu** [comment]
:+1:
