### ISSUE TITLE
Add access true/false option in og_context_plugin_argument_default_group_context after og_context() rewrite in 7.x-2.8

### ISSUE THREAD

**Issue by alesrebec** [Gizra/og#121]
> Copied from https://www.drupal.org/node/2720403

Since the big og_context() changes made in OG 7.x-2.8 anonymous users, anonymous users get FALSE on og_context() call. Prior to that version, the return was an array with og gid in context.
My understanding is that this is (at least a minor) breakage of an OG 7.x-2.x API.

To keep the required behaviour you have to rewrite all og_context() function calls and include "$check_access = FALSE" so the access check is skipped and og_context() function acts like it was until 7.x-2.8.

This was added:

```
 * ...
 * @param bool $check_access
 *   Determines if access to the group should be done. Defaults to TRUE.
 ...
 */
function og_context($group_type = 'node', $group = NULL, $account = NULL, $check_access = TRUE) {
...
}

```

I had this bug somewhere deep in a complex site. I wouldn't even noticed it myself. I got a support ticket created that there's something wrong on that page.
There are thousands of sites using OG and only question is how many sites are broken because of this change.

**Comment by alesrebec** [comment]
Closed.
https://www.drupal.org/node/2720403#comment-11186941

**Comment by alesrebec** [comment]
Copied from: https://www.drupal.org/node/2720403#comment-11195599

> @amitaibu, I did changed all function calls to og_context() with $access_check set to FALSE (as suggested).
> The problem that appeared after that was in og_context_plugin_argument_default_group_context.inc views handler where an option to select between Check access (YES or NO) was missing in views contextual filter handler for og context.
> 
> I had two options. Create an own handler which would be a copy of this one with added option to select Check access or patch this one, the same way og_context() function was patched with $check_access parameter which is set to TRUE by default.
> Actually this should come in with that og_context() patch by Helena.
> If we allow to call og_context() with $check_access set to FALSE, we need to allow this in views handler too.

**Comment by amitaibu** [comment]
Thanks. Can you please close the d.o. issue and open a PR

**Comment by kyletaylored** [comment]
I went ahead and closed a D.O ticket that was related to this patch as well.

[Adding non-Required OG Relationship to View Causes View to Display no Results for Anonymous](https://www.drupal.org/node/2339953#comment-12163432)

**Comment by alesrebec** [comment]
Pull request is still unmerged in #122 
Should be released in version 7.x-2.10.

We can keep a list of related issues in one place.
I was able to find a lot of them! This issue was breaking people's sites after version 7.x-2.8.

- https://www.drupal.org/node/2720403
- https://www.drupal.org/project/og/issues/2720337
- https://www.drupal.org/node/1952980
- https://www.drupal.org/project/og/issues/2724643
- https://www.drupal.org/project/og/issues/2717489
- https://github.com/Gizra/og/issues/123

**Comment by alesrebec** [comment]
Closing this issue in favour of more restrictive approach by default described in #122.
