### ISSUE TITLE
og_migrate Not Part of the Project?

### ISSUE THREAD

**Issue by wellspun** [Gizra/og#139]
I'm upgrading a site from 6 to 7.50 and am upgrading OG along with it.  As per the instructions, "Q: How should I update from Drupal 6? A: Run update.php; Enable the og-migrate module and execute all the migration plugins." I've run update.php but then can't seem to find the og-migrate module.  It doesn't appear to show up in the Module list and I can't find a module declaration anywhere in the code.  Is it possible to run the module code that does exist directly?  Or am I doing something wrong?

I did use the latest version that shows up on Drupal.org: v2.9.

Any help would be very appreciated.  Thanks!

**Comment by MPParsley** [comment]
You can provide custom migrations using the [migrate module](http://drupal.org/project/migrate).
