### ISSUE TITLE
"your groups" and "other groups" within admin OG audience field do not respect cardinality of 1.

### ISSUE THREAD

**Issue by jastraat** [Gizra/og#14]
Scenario:
My content type contains an OG group reference field with cardinality limited to 1 so that content can only be associated with a single group.
A groups administrator sees a more complex field for OG audience that has two parts: "your groups" and "other groups" (either auto-complete or select).
When an administrator selects a value in one of the two fields but doesn't manually remove the value from the other field and saves the node, the following error is generated:

OgException: OG membership can not be created in entity <em class="placeholder">node</em> and bundle <em class="placeholder">freeform</em> using the field <em class="placeholder">og_group_ref</em> as the field cardinality is set to 1. in OgMembership->save() (line 69 of /sites/all/modules/contrib/og/includes/og.membership.inc).

Ideally, there would be form validation that prevents the node form from being submitted when cardinality is 1 and more than one value for group audience is selected. It would be even better if (with cardinality 1) after selecting a value for "other groups" that "your groups" was set with JS to "none" (and the reverse).

**Comment by amitaibu** [comment]
Hi @jastraat 
It would be great if you could provide a PR with such a validation in [here](https://github.com/Gizra/og/blob/7.x-2.x/includes/og.field.inc#L276)

**Comment by jastraat** [comment]
Hi @amitaibu, I have a patch for this, but I'm afraid I'm not sure how to submit it in the context of github - only how it was done on drupal.org. 

I've uploaded the patch for review here: https://www.drupal.org/node/2447791

**Comment by MPParsley** [comment]
@amitaibu @pfrenssen, I assume we can we close this one in favor of #160 ?
