### ISSUE TITLE
Groups as Entities? 

### ISSUE THREAD

**Issue by EricaMZDM** [Gizra/og#15]
I realize this is a late in the game ask/question,  but is there any good reason for groups being nodes with specific fields attached,  instead of a custom entity type? I would think it would ultimately make them a lot more manageable.

**Comment by geek-merlin** [comment]
The OG aproach of _being a group is a behavior_ (thus any entity can be a group) has the implication it can be combined with any other behavior. Tieing behaviors to specific implementations is a bad antipattern.
Think of it as the architecture equivalent of "Program against an interface, not a implementation".

**Comment by MPParsley** [comment]
If you want groups as an entity you may consider https://www.drupal.org/project/group.

I suggest we close this issue.

**Comment by amitaibu** [comment]
We can close this, I'd just note that OG since 7.2 allows any entity to be a group (unlike group module that forces a Group entity to act as the group).
