### ISSUE TITLE
og_get_groups_by_user not working as documented

### ISSUE THREAD

**Issue by DavidHernandez** [Gizra/og#152]
The og_get_groups_by_user documentation says it returns an array of group IDs or an empty array. But under certain circumstances, returns NULL.

**Comment by DavidHernandez** [comment]
Seems that the issue was already on drupal.org: https://www.drupal.org/node/2569471

**Comment by jacobembree** [comment]
This pull request can now be closed because of b7a6be12373d9ef9996e09bc6d524a31390004df.
