### ISSUE TITLE
Broken Kernel and Functional tests

### ISSUE THREAD

**Issue by dakala** [Gizra/og#154]
I have noticed that OG kernel and functional tests are failing,mostly with a PHPUnit_Framework_Exception: sh: : command not found error. However, this is also happening with core kernel and functional tests.

Not sure if it isn't an issue with my environment. Screenshots attached.

![wikitest](https://cloud.githubusercontent.com/assets/285543/18155249/be248bea-7003-11e6-923a-721190bf744e.png)
![itemwithoutfeedtest](https://cloud.githubusercontent.com/assets/285543/18155247/be201f2e-7003-11e6-901f-9a4f25458590.png)
![placeholdermessagetest](https://cloud.githubusercontent.com/assets/285543/18155248/be232520-7003-11e6-9c02-a6ad4da53cbd.png)

**Comment by amitaibu** [comment]
We are running the tests via command line. Setup can be a little annoying (especially for Functional tests), but then you can run things like:

`./vendor/phpunit/phpunit/phpunit  -c ./core/phpunit.xml.dist ./modules/og/tests/src/Unit`

For Kernel tests, make sure your mysql host is set to `127.0.0.1` and not `localhost`

**Comment by dakala** [comment]
I'll give that a go.

**Comment by dakala** [comment]
Tests now running. Had to add some environment variables to phpunit.xml.dist but I'm getting greens (and reds).
