### ISSUE TITLE
Why do we addTag('node_access') in getGroupIds()  ?

### ISSUE THREAD

**Issue by chx** [Gizra/og#175]
I am ... well not quite porting `og_access` but writing my own little module implementing node access controlled groups (and their content) and it failed because `getGroupIds()` adds `addTag('node_access")` which obviously causes empty results to be returned during `node_access_rebuild`. I believe the exact opposite, `->accessCheck(FALSE)` is better here.

**Comment by amitaibu** [comment]
I'm not seeing an `addTag` in the current code base - can you link to it please

**Comment by chx** [comment]
OK the access check is gone fromhttps://github.com/Gizra/og/blob/8.x-1.x/src/MembershipManager.php#L189 here but you still need the ->accessCheck(FALSE)

**Comment by amitaibu** [comment]
Yes, it seems it should be added there. Care to PR?

**Comment by chx** [comment]
PRs are very complicated when I already have a few patches in production (mostly the context part)... let me see what I can.

**Comment by chx** [comment]
And i only have push rights to your personal repo not this one.

**Comment by amitaibu** [comment]
Yeah, we push the code to `amitaibu/Og` and create a PR from there.

**Comment by chx** [comment]
Did that

**Comment by chx** [comment]
https://github.com/Gizra/og/pull/178

**Comment by pwolanin** [comment]
Looks like this is fixed?

**Comment by amitaibu** [comment]
Should be :)

**Comment by weitzman** [comment]
Seems like its not there right now https://github.com/Gizra/og/blob/f8360f4cd1d3a47233d68efa4362d3a660967924/src/MembershipManager.php

**Comment by amitaibu** [comment]
Yeah, that code was removed.
