### ISSUE TITLE
Group manager membership type cannot be defined

### ISSUE THREAD

**Issue by krystalcode** [Gizra/og#183]
In the Drupal 7 version of the module, the owner of the group is subscribed to the group in the og_entity_insert hook that uses the og_group function, which in turns uses the first suitable field that defines the membership type. There is no possibility to define the field, and therefore the membership type, that should be used to subscribe the group owner. The only way to do so would be to hack the og module and define custom application logic, which would not belong there.

What would be the best way to define such configuration? It could be stored in a variable, but such configuration would need to be per group type, so I'm not sure if this would be the right way.

I can create a PR once we agree on the correct way to implement this.

**Comment by amitaibu** [comment]
Ugly, but if you have specific needs you can `hook_implements_alter()` - remove OG's logic, and create your own hook to take care of things.
