### ISSUE TITLE
OG fields

### ISSUE THREAD

**Issue by RoySegall** [Gizra/og#188]
While D7 had a bad UX for adding OG fields I'm suggesting some improvements for the overall look and how we can add/remove fields much more clearly:

![sample_project_-_first_page_ _moqups](https://cloud.githubusercontent.com/assets/1222368/18784425/b26a4ec2-819a-11e6-924f-1e7dbab542cf.png)

What do you think?

**Comment by amitaibu** [comment]
Thanks for looking at it, but I think you didn't read my last OG post ;)
Let's start by not adding this ui.

**Comment by RoySegall** [comment]
Not fully. I gave it another shot and I can see where you going with this. But there must be way we can simplify the adding of fields to entities. Code is no the best way to do it. What about Drush command? Drupal console integration? Adding a part to the mange field part of each entity?
