### ISSUE TITLE
\Drupal\og\Routing\RouteSubscriber should use interfaces as type hints in the constructor

### ISSUE THREAD

**Issue by brummbar** [Gizra/og#192]
While enabling the Webprofiler module, I got errors due to the type hints used in the RouteSubscriber constructor.
Interfaces should be used instead of classes as injected services:
- `EntityTypeManagerInterface` should be used instead of `EntityTypeManager`;
- `EventDispatcherInterface` should be used instead of `ContainerAwareEventDispatcher`.

**Comment by zerolab** [comment]
This can be closed since #193 was merged in.
