### ISSUE TITLE
Rename GetGroupsTest class to GroupMembershipManagerTest to match its file name

### ISSUE THREAD

**Issue by brummbar** [Gizra/og#195]
I faced the following failure in the Og test suite:

> PHP Fatal error:  Uncaught ReflectionException: Class Drupal\Tests\og\Kernel\Entity\GroupMembershipManagerTest does not exist in ..../core/modules/simpletest/src/TestDiscovery.php:328

The class has to be renamed to match its filename.

**Comment by MPParsley** [comment]
Fixed in #194.
