### ISSUE TITLE
More Drupal console integration

### ISSUE THREAD

**Issue by RoySegall** [Gizra/og#196]
After the first DrupalConsole integration is merged I have more ideas:
- [ ] Define an entity as a Group - #210
- [ ] Enable/disable context plugins
- [ ] Change the weights of the context plugins
- [ ] Generate OG permissions
- [ ] Generate OG role
- [ ] Revoke/Add permission to OG role
- [ ] Add OG membership type
- [ ] Add fields to OG membership(we might have commands to add fields in Drupal Console core's)
- [ ] Generate OG field
- [ ] Generate orphan delete
- [ ] Scaffold a group and group content type and add audience field to the group content

**Comment by MPParsley** [comment]
In #640 the support for Drupal Console was removed since it was conflicting with Drupal 9 (ref commit aa3b87c).

Closing this.
