### ISSUE TITLE
OG audience filed population

### ISSUE THREAD

**Issue by RoySegall** [Gizra/og#2]
The OG audience field(AKA og_group_ref) is a special field. It's a field that populated like all the other fields. Every time there is a change in the field we need to remove/update/insert og membership entity.

This split into:
- [ ] When populating the field programatically.
- [ ] When editing an entity from the UI we need to create manually the form elements.

**Comment by pfrenssen** [comment]
This is no longer needed. We are now using a regular entity reference field type for the group audience field.
