### ISSUE TITLE
Follow up RTBC-d issues on D.o. regularly

### ISSUE THREAD

**Issue by mxr576** [Gizra/og#225]
As it is written, development and issue tracking is happening here, but some Drupal community members still uses D.o's issue queue to submit and fix issues. D.o. contains plenty valuable patches for common issues which are in the queue since ages, but they still haven't been fixed in latest Organic Groups releases. Please follow up these issues and commit these patches to og.module.

https://www.drupal.org/project/issues/og?status=14

**Comment by amitaibu** [comment]
Thanks, I know about this list. Getting the time to go over all of them is what's missing ;)

**Comment by amitaibu** [comment]
(btw, most of those RTBC issues don't have tests, which is usually what keeps them form getting in)
