### ISSUE TITLE
Implement group roles and permissions (Class "\Drupal\og_ui\Form\OgPermissionsForm" does not exist)

### ISSUE THREAD

**Issue by rogerwalt** [Gizra/og#232]
Hi

I just installed `https://ftp.drupal.org/files/projects/og-8.x-1.x-dev.tar.gz` to a Drupal 8.2.5 project. I followed the instructions, can display groups etc. Both modules are enabled:

![screenshot from 2017-01-11 09 20 57](https://cloud.githubusercontent.com/assets/1636054/21840742/640c22f0-d7df-11e6-91f5-aa6be438417c.png)

When calling `/admin/config/group/permissions/node/group`, the following error occurs:
```
InvalidArgumentException: Class "\Drupal\og_ui\Form\OgPermissionsForm" does not exist. in Drupal\Core\DependencyInjection\ClassResolver->getInstanceFromDefinition() (line 24 of core/lib/Drupal/Core/DependencyInjection/ClassResolver.php).
```

I checked and I only have the following files:
```
tree modules/og/og_ui/src
modules/og/og_ui/src
├── BundleFormAlter.php
├── Controller
│   └── OgUiController.php
└── Form
    └── AdminSettingsForm.php

2 directories, 3 files
```

How to proceed?

Cheers,
Roger

**Comment by amitaibu** [comment]
Hi, this form is not implemented yet. @pfrenssen has started some work in https://github.com/amitaibu/og/pull/196

**Comment by MPParsley** [comment]
The work is now continued in #243.

**Comment by MPParsley** [comment]
Closing this as a duplicate in favor of #238.
