### ISSUE TITLE
Bug in checking entity operation access (D8)

### ISSUE THREAD

**Issue by pwolanin** [Gizra/og#249]
I am trying a simple test where I give a user a permissions to "Foo: Create new content" and "Foo: Edit own content"  where "Foo" is group content and the user is a member of the "Lab" group.

This does not work as expected - the content can be created ad is added to the group, but the user cannot edit the group content despite being the node owner.

It appears the bug is in:

`\Drupal\og\OgAccess::userAccessGroupContentEntityOperation`

On Line 355:
```
        $user_access = $this->userAccess($group_entity, $permission->getName(), $user);
```

This is incorrect for 2 reasons - we are supposed to be checking permission for operation on the $group_content_entity not $group_entity, plus the method `\Drupal\og\OgAccess::userAccess` is for checking access to operate on a group, not on group content.

Does this analysis seem right?

**Comment by pwolanin** [comment]
Ok, after debugging some more i think the above hypothesis is a bit wrong - it does seem like that is the right method call, though it feels as though there is intermixed logic checking for group-level permissions vs other permissions

I have 'node_access_strict' enabled (which is the default I think).  

It seems the problem is that the OG role object is returning no permissions at all.

The admin UI implies that the global permissions are inherited by every user in the group context:

> When enabled Organic groups will restrict permissions for creating, updating and deleting  according to the Organic groups access settings. Example: A content editor with the Edit any page content permission who is not a member of a group would be denied access to modifying page content in that group. (For restricting view access use the Organic groups access control module.)


But looking at the code, I don't see any way that's going to happen, and there is no ui for adding permissions either.  What am I missing here.  It doesn't seem like this works?

**Comment by zerolab** [comment]
@pwolanin see #231 and comments for the roles/permissions UI.

**Comment by pwolanin** [comment]
Ok, I think I was just confused by the admin UI text.

**Comment by zerolab** [comment]
It did take us by surprise as well.

Btw, the PR is #243, not #231, but both are useful

D
