### ISSUE TITLE
Reset MembershipManager cache on membership deletion

### ISSUE THREAD

**Issue by zerolab** [Gizra/og#257]
Currently when a membership is updated, several caches are reset:

```php
    Og::reset();
    \Drupal::service('og.access')->reset();

    // Invalidate the group membership manager.
    \Drupal::service('og.membership_manager')->reset();
```

However, if you remove someone's membership the `MembershipManager` cache stays intact which leads to all kinds of odd issues. We have to resort to 

```php
/**
 * Implements hook_ENTITY_TYPE_delete().
 */
function my_module_og_membership_delete(OgMembershipInterface $membership) {
  // Invalidate the group membership manager.
  \Drupal::service('og.membership_manager')->reset();
}
```

I propose:

- reset  the `MembershipManager` in `OgMembership::postDelete()`
- extend `MembershipManager::reset()` to be more granular. i.e. invalidate only the relevant user cache entries, rather than everything. 
  - keys: `getMemberships:UID:active(|blocked|pending)`

If you are happy with the proposal, happy to provide PR

**Comment by pfrenssen** [comment]
This was fixed some time ago in #480.
