### ISSUE TITLE
Making OG roles disregard bundles

### ISSUE THREAD

**Issue by jludwig** [Gizra/og#264]
At BioRAFT, we have our own mechanism for determining what roles should be associated with what content. Furthermore, we may have very different bundles across different sites that require the same roles. Because of this, it makes sense for our OG roles to not be tied to a specific bundle.

I see two ways of doing this:

(1) Overriding the services that make OG roles care about bundles, and saving an empty bundle to any role added.

(2) Synchronizing roles across all bundles automatically.

The second approach is probably easier and safer, but it seems like it saves a lot of data that really isn't useful to us.

What would be recommended path forward for our use case? Does this edge-case apply to anyone else, and if so would it be worth making into a submodule or a configuration that can be contributed back?

Thanks!
-Justin Ludwig

**Comment by amitaibu** [comment]
The thing is that I think a role across different group types, while it might have the same name it actually represents something else.

That is, like Drupal core, a role is just a collection of permissions. But if we are talking about different bundles, then we are also talking about different set of permissions. For example, in one group you'll have "edit own article", and in another "edit own page".

So, in fact roles by themself are just a mechanism to determine permissions. For that, you can bake your own logic, with or without roles.

I hope it helps :)
