### ISSUE TITLE
og_entity_insert does not care if there is a memberhsip

### ISSUE THREAD

**Issue by idimopoulos** [Gizra/og#295]
I have the following issue:
Og, since it wants to behave agnostically, uses hook_entity_insert in order to create a membership for the user that creates the memberhsip (if the entity inherits the publisher interface).

The problem comes by the fact that this blocks users from tampering with the membership on creation. The only way that a user can interfere is that his module is named something that starts with later than 'o' so that it's listed after og, and use the hook_entity_insert in order to catch and alter the membership.

In my case, I want to use the hook_ENTITY_TYPE_insert, but since og does not check for a membership before creating one, an exception is thrown as there is an active membership.

Proposed solution:
Since og_entity_insert simply creates and saves a membership, escape early if there is already a membership found.

**Comment by pfrenssen** [comment]
Fixed in #296.
