### ISSUE TITLE
OgRole::delete() compares of Role ID and role constants that won't ever succeed

### ISSUE THREAD

**Issue by joachim-n** [Gizra/og#305]
```
    if (in_array($this->id(), [self::ANONYMOUS, self::AUTHENTICATED]) && $this->groupTypeManager()->isGroup($this->getGroupType(), $this->getGroupBundle())) {
```

The role ID can't ever match either of those -- see https://github.com/Gizra/og/issues/304.

**Comment by zerolab** [comment]
note that latest dev doesn't have the comparison anymore -- https://github.com/Gizra/og/blob/8.x-1.x/src/Entity/OgRole.php#L256

**Comment by joachim-n** [comment]
Huh. I checked 8.x-1.x before filing. Is d.org's copy out of date compared with what's on github?

**Comment by amitaibu** [comment]
Hi @joachim-n welcome to OG :)

It's seems to be updated (Peter & I push it there whenever we merge an issue)
