### ISSUE TITLE
OGMembership entity should implement EntityOwnerInterface

### ISSUE THREAD

**Issue by joachim-n** [Gizra/og#308]
OG membership entities have an owning user, who the membership is about.

This should implement EntityOwnerInterface for consistency with other entity types.

(The matter of whether getUser() and setUser() should be deprecated can be a follow-up; for now they can wrap getOwner() and setOwner()).

**Comment by joachim-n** [comment]
PR: https://github.com/Gizra/og/pull/309

**Comment by pfrenssen** [comment]
Fixed in #309.
