### ISSUE TITLE
Group owner membership is activated on every group save

### ISSUE THREAD

**Issue by willzyx-dev** [Gizra/og#321]
Original issue on d.o https://www.drupal.org/node/2916057

When a user is the owner of a group (a node for instance) and his membership status is "BLOCKED" saving the group entity cause the membership status to be moved to "ACTIVE".

from a first analysis the problem seems caused by `og_entity_update`

```php
/**
 * Implements hook_entity_update().
 */
function og_entity_update($entity, $entity_type) {
  if (!og_is_group($entity_type, $entity)) {
    return;
  }

  list($id, , $bundle) = entity_extract_ids($entity_type, $entity);
  if (!empty($entity->uid) && !og_is_member($entity_type, $entity, 'user', $entity->uid)) {
    // Subscribe the group manager, in case the owner changed.
    og_group($entity_type, $id, array('entity' => $entity->uid));
    // Assign roles to group manager.
    $name = 'og_group_manager_default_rids_' . $entity_type . '_' . $bundle;
    if ($rids = variable_get($name)) {
      foreach ($rids as $rid) {
        og_role_grant($entity_type, $id, $entity->uid, $rid);
      }
    }
  }
```

this part of code seems to have 2 main problems:
1) the second argument passed to og_is_member() function is the whole entity not the entity id - was solved in [#2411041: Group manager always given default default role as og_is_member arguments wrong](https://www.drupal.org/node/2411041)
2) the og_is_member() function is called without specify the membership states, the default value for this parameter is an array containing OG_STATE_ACTIVE; this means that if entity owner has not an ACTIVE membership (eg he/she is blocked) he is not considered a member of the group and a new ACTIVE membership is created or if it already exists it is updated changing the status to ACTIVE.

This seems wrong... If the group owner has blocked status saving the group entity should change his membership status. I'm missing something?

**Comment by MPParsley** [comment]
This is fixed in #322.
