### ISSUE TITLE
make it easier to check for a role on a membership -- add a hasRole() method?

### ISSUE THREAD

**Issue by joachim-n** [Gizra/og#327]
OgMembership::getRoles() uses the role field's referencedEntities() method, which means that what you get back isn't keyed by role ID.

That makes it fiddly to check for a particular role.

Possible fixes:

- change getRoles() to key by ID
- add a hasRole() method + also document getRoles() to say the key is numeric.

**Comment by amitaibu** [comment]
> change getRoles() to key by ID

You mean key by role Id (==name)?

I believe that core's `getRoles` is returning it indeed by role ID, and if that's the case we should follow core (which is always our guideline).

**Comment by joachim-n** [comment]
> You mean key by role Id (==name)?

Yup, that's what I meant.

> I believe that core's getRoles is returning it indeed by role ID, and if that's the case we should follow core (which is always our guideline).

The plot thickens... https://api.drupal.org/api/drupal/core%21modules%21user%21src%21Entity%21User.php/function/User%3A%3AgetRoles/8.5.x gets you an array of IDs only, not the entities.

**Comment by amitaibu** [comment]
One would argue that core should have call it `getRoleIds`... 😉 

Anyway, we should adapt our code to be as close to core as possible

**Comment by joachim-n** [comment]
> One would argue that core should have call it getRoleIds... 😉

Yup, definitely.

How close can we get it?

If we change getRoles() to return IDs to match core, then we lose the ability to get the role entities easily. We could add a new method to get the role entities, it just needs a name.... :/

I think we should also add a hasRole() method.

**Comment by amitaibu** [comment]
I guess maybe we could be better than core here and keep `getRoles` to get the entities and `getRoleIds` to get the IDs

**Comment by pfrenssen** [comment]
See also #315.

**Comment by MPParsley** [comment]
This seems to have been resolved:
```
  /**
   * Gets all the referenced OG roles.
   *
   * @return \Drupal\og\Entity\OgRole[]
   *   List of OG roles the user own for the current membership instance.
   */
  public function getRoles(): array;

  /**
   * Gets all the referenced OG role IDs.
   *
   * @return string[]
   *   List of OG role IDs that are granted in the membership.
   */
  public function getRolesIds(): array;

  /**
   * Checks if the membership has the role with the given ID.
   *
   * @param string $role_id
   *   The ID of the role to check.
   *
   * @return bool
   *   True if the membership has the role.
   */
  public function hasRole(string $role_id): bool;
```
