### ISSUE TITLE
MembershipManager::getMemberships() and getMembership() don't document how to get all states

### ISSUE THREAD

**Issue by joachim-n** [Gizra/og#335]
```
   * @param array $states
   *   (optional) Array with the state to return. Defaults to active.
```

This doesn't tell me how to get all states.

Looking at the code, an empty array will do it.

**Comment by joachim-n** [comment]
Revisiting this, it occurs to me that a new constant OgMembershipInterface::STATE_ANY would be clearer.

**Comment by amitaibu** [comment]
`OgMembershipInterface::STATE_ANY` sounds like a good idea.

**Comment by pfrenssen** [comment]
Instead of a new string constant, how about defining an array constant `OgMembershipInterface::STATES` that contains the available states?

```
  /**
   * An array containing all possible group membership states.
   */
  const STATES = [self::STATE_ACTIVE, self::STATE_PENDING, self::STATE_BLOCKED];
```

This would be clearer and easier to implement I think. It also has use cases wherever you need to consult or loop over the full list of states in code.

**Comment by amitaibu** [comment]
Yeah, I like this STATES const better
