### ISSUE TITLE
D7 - Remove dependency on user audience field.

### ISSUE THREAD

**Issue by joelpittet** [Gizra/og#354]
`og_get_best_group_audience_field()` is called in various (5) places.  It makes an implicit dependency on a user field that otherwise doesn't need to exist(from what I gather) for membership. 
And that field shows all the groups a user is subscribed to, which doesn't scale well for admin for example who is on all of them.

I proposing removing this dependency.

Any words of wisdom, institutional knowledge before diving into this?

**Comment by amitaibu** [comment]
Hi @joelpittet !

> user field that otherwise doesn't need to exist(from what I gather) for membership

It's a (bad) design decision that the membership can also be set via field API.

As D7 is quite stable I'm not too eager in introducing much changes - and concentrate on D8 (which we removed those fields). Is the existing dependency blocking you?
Anyway, with the above said and warned, if you really require this feature, and are willing to help drive this effort I'm not going to stop you 😉  - but worth having a very early WIP PR, just so we can see if it's taking the right approach.

**Comment by joelpittet** [comment]
Hey @amitaibu, it's blocking in the sense that admin is getting assigned to every group (gotta look into that) and that field is not scaling well with that.  Thanks for the warning, I'll take that into consideration:)

**Comment by amitaibu** [comment]
> it's blocking in the sense that admin is getting assigned to every group

AFAIK that should not be the case. Admin, as a user with `administer group` has the OG widget that allows them to *select* each group (via autocomplete) -- but they are not part of it.

**Comment by joelpittet** [comment]
I found out why, because the groups get generated by the admin, and because they are the author of the group node they are kept as belonging to the group!

**Comment by amitaibu** [comment]
In that case, maybe you can have custom code to ungroup the admin.

**Comment by joelpittet** [comment]
Thanks for helping me, I realized I don't need to have my admin own the content and set the groups to anonymous. Soo much nicer. Since it's gone in 8 I won't bother trying to untangle that field.

Thanks for your help @amitaibu!
