### ISSUE TITLE
Need Support

### ISSUE THREAD

**Issue by vtulse** [Gizra/og#355]
We are porting "Ip Path Access" to D8 and we have used og module og_is_member() in our module.

Let us know have you rewritten this function or is it ready to use in our module?

Please, Guid us?

**Comment by alesrebec** [comment]
In OG D8 you have **isMember()** method in MembershipManager class.

Check MembershipManager class to see where it's defined https://github.com/Gizra/og/blob/8.x-1.x/src/MembershipManager.php 

```
public function isMember(EntityInterface $group, AccountInterface $user, array $states = [OgMembershipInterface::STATE_ACTIVE]) {
    $group_ids = $this->getUserGroupIds($user, $states);
    $entity_type_id = $group->getEntityTypeId();
    return !empty($group_ids[$entity_type_id]) && in_array($group->id(), $group_ids[$entity_type_id]);
  }
```

and here in OgAccess https://github.com/Gizra/og/blob/8.x-1.x/src/OgAccess.php how it's implemented:

`$this->membershipManager->isMember($group, $user, [OgMembershipInterface::STATE_BLOCKED])`

**Comment by vtulse** [comment]
Thank you for help.
