### ISSUE TITLE
Automatically created role actions trigger an error on configuration synchronization

### ISSUE THREAD

**Issue by MPParsley** [Gizra/og#363]
Whenever a new role is created an action to add and delete that role are created in og_og_role_insert().
When exported to configuration and synced on deploy you get the following error:

Synchronized configuration: create system.action.og_membership_add_single_role_action.editor.

The import failed due to the following reasons:
Configuration-entity 'system.action.og_membership_add_single_role_action.editor' deleted and replaced

When the role is added the actions are automatically created with a different uuid so the sync will try to delete and recreate them.

We should add a check to see if the config is syncing and prevent the creation of the actions in that case (ConfigEntityInterface::isSyncing).

To do this OgRoleInterface may need to extend ConfigEntityInterface, it's not clear why this isn't the case?

**Comment by DiDebru** [comment]
I've added a fix to my PR https://github.com/Gizra/og/pull/439 , I run into this , too.

**Comment by MPParsley** [comment]
We can close this as it's fixed in #231 and #439.
