### ISSUE TITLE
ajax submit button breaks entity prepopulate of group admin audience field "other groups"

### ISSUE THREAD

**Issue by jastraat** [Gizra/og#37]
To recreate:
1) log in as an admin with "administer groups" permission
2) in a group where the logged in user is not a member, create new content using a required group audience field with entity prepopulate via the URL.
3) Despite not being a member, the group appears in the 'default' field as part of the combo audience field for group administrators.
5) Click 'upload' on a file/image field within the group content node form. The default field will still show the prepopulated group in 'your groups'. (If no ajax submit buttons are clicked, saving works.)
6) Attempt to save.
7) Your groups is cleared, and the node form throws the following error: "An illegal choice has been detected. Please contact the site administrator." - from line 1388 in includes/form.inc - because the value of the prepopulated group is no long in the options for 'your groups'.
8) This error is compounded because after the error, it's no longer possible to select the prepopulated group in EITHER 'your groups' or 'other groups'. If selected in 'other groups', the referenced group throws "The referenced group (@type: @id) is invalid." from OgBehaviorHandler.class.php because the prepopulated value is not listed in the results from entityreference_get_selection_handler() any longer.

Note that I tried this with the admin part of the audience field as both an autocomplete and as a select field. I also tested this with the latest dev version of entityreference_prepopulate that contained a patch for a different ajax error. (http://cgit.drupalcode.org/entityreference_prepopulate/commit/?id=41ed253) The error was present in all cases.

**Comment by amitaibu** [comment]
Hi @jastraat , are you going to work on this? :)

**Comment by jastraat** [comment]
@amitaibu - I think I just solved the problem, and it's not in OG but in entityreference_prepopulate.

Since I believe this is the same issue described in https://www.drupal.org/node/2399755, I'm going to post my patch there.

**Comment by amitaibu** [comment]
Sababa :)

**Comment by jastraat** [comment]
I'd be much obliged if you'd review my patch -  :)
https://www.drupal.org/node/2447657
