### ISSUE TITLE
When an entity is not part of a group but the type could be part of it, the access is blocked

### ISSUE THREAD

**Issue by DavidHernandez** [Gizra/og#373]
The `og_entity_access` hook checks if a entity type and bundle can be content of a group. But it does not check if the actual entity is content of a group. This causes some entities with an audience field marked as not required be blocked by the hook implementation.

Here are some steps to replicate the issue:
- Create a group entity.
- Create a new content type with the audience field, mark it as not required.
- Use an user that is not admin, to create a new node of that content type but do not fill the audience field.
- Try to edit the node. It will return an access denied.

**Comment by MPParsley** [comment]
It seems this has been fixed in #374.
