### ISSUE TITLE
Call to a member function getEntityTypeId() on string in og/src/Plugin/OgGroupResolver/RouteGroupResolver.php on line 27

### ISSUE THREAD

**Issue by MPParsley** [Gizra/og#379]
I have the latest core content_moderation module enabled. When clicking on a revision in the revisions tab I get the following error:

```
PHP message: Error: Call to a member function getEntityTypeId() on string in modules/contrib/og/src/Plugin/OgGroupResolver/RouteGroupResolver.php on line 27
```

```
  public function resolve(OgResolvedGroupCollectionInterface $collection) {
    $entity = $this->getContentEntity();
    if ($entity && $this->groupTypeManager->isGroup($entity->getEntityTypeId(), $entity->bundle())) {
      $collection->addGroup($entity, ['route']);

      // We are on a route that matches an entity path for a group entity. We
      // can conclude with 100% certainty that this group is relevant for the
      // current context. There's no need to keep searching.
      $this->stopPropagation();
    }
  }
```

$this->getContentEntity(); returns the id of the node, not the node object.

**Comment by zerolab** [comment]
👍 @MPParsley 
I can confirm this. Have it in a list of To-Dos for our project, but never got open issue.

**Comment by MPParsley** [comment]
@zerolab could this be related to https://www.drupal.org/project/drupal/issues/2730631 ?

**Comment by zerolab** [comment]
That is exactly the issue. https://www.drupal.org/files/issues/2730631-41.patch solves this, however the d.o. issue has further discussions and there seems to be an indication https://www.drupal.org/project/drupal/issues/2730631#comment-12712386 may be the direction it goes in.

**Comment by MPParsley** [comment]
Closing this as https://www.drupal.org/project/drupal/issues/2730631 is now committed to Drupal 9.3
