### ISSUE TITLE
State API shouldn't be used for caching

### ISSUE THREAD

**Issue by MPParsley** [Gizra/og#440]
In `GroupTypeManager::refreshGroupRelationMap()` state API is used to cache the map:

```
    // Cache the map.
    $this->state->set(self::GROUP_RELATION_MAP_CACHE_KEY, $this->groupRelationMap);
``` 

We shouldn't use state for caching. It can break things when another entity type has an og_reference field (e.g. og_menu).

A simple workaround is to clear the state manually:

``` 
drush state:delete og.group_manager.group_relation_map
```

**Comment by pfrenssen** [comment]
Good find! We should use the Cache API for this.
