### ISSUE TITLE
Error on Group Edit Permissions - Drupal 8.6.4 

### ISSUE THREAD

**Issue by kclarkson** [Gizra/og#454]
I have just installed OG alpha2 on simplytest.me. It is using 8.6.4 

When visiting admin/config/group/permissions/node/event I receive a white screen with the message `The website encountered an unexpected error. Please try again later.`

**Comment by zerolab** [comment]
You likely need #243, not sure how that would work with simplytest.me
 It would also help if you could provide further errors (e.g. what is the associated PHP error in the database log?)

**Comment by MPParsley** [comment]
This is a duplicate of #232, the ui forms to manage permissions aren't developed yet. As @zerolab mentioned, you'll need #243.
