### ISSUE TITLE
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'og_membership.field_og_ref_target_id' in 'on clause'

### ISSUE THREAD

**Issue by reinette** [Gizra/og#46]
Details here: https://www.drupal.org/node/1890370
Patch here: https://www.drupal.org/files/issues/add-gid-to-relationship-field-1890370-34.patch

**Comment by amitaibu** [comment]
Hi, if already hereon GitHub Can you please create a PR

**Comment by amitaibu** [comment]
sorry, actually going to look at them on d.o
