### ISSUE TITLE
Release 8.x-1.0-alpha3

### ISSUE THREAD

**Issue by pfrenssen** [Gizra/og#515]
I think the time is right to make the 8.x-1.0-alpha3 release. We have added support for Drupal 8.7 which is already released, and a whole slew of small improvements and bug fixes have been made.

There haven't been any new bugs reported in the past couple of weeks since our last sprint, so it looks like the latest 8.x-1.x is reasonably stable.

This week there is a new sprint planned at Drupal Dev Days. I'm thinking if we tag a release now we have more freedom to move quick during the sprint without causing too much trouble to people who are currently on the 8.x-1.x-dev branch because they need the Drupal 8.7 support.

After the sprint ends we can wait a few weeks and release alpha4.

**Comment by pfrenssen** [comment]
@amitaibu do you agree to make the alpha3 release today?

**Comment by amitaibu** [comment]
Sure, go ahead

**Comment by pfrenssen** [comment]
8.x-1.0-alpha3 has been released both on Github and drupal.org!
