### ISSUE TITLE
Disable CodeClimate checks

### ISSUE THREAD

**Issue by pfrenssen** [Gizra/og#517]
I want to sprint on OG during Drupal Dev Days but I am getting false positives from CodeClimate. It is complaining about things that are not in the Drupal coding standards.

Let's disable it until it is ready for use, i.e. not throwing any false positives.

**Comment by MPParsley** [comment]
Hi @pfrenssen, I don't have administration access but if you want to disable codeclimate it needs to happen on https://codeclimate.com/github/Gizra/og. @amitaibu?

**Comment by amitaibu** [comment]
Sure, it can be disabled.

**Comment by pfrenssen** [comment]
We can enable it again when we had time to improve it a bit more. Just now for the code sprint at Drupal Dev Days I want to try to get some new people to contribute and committing failing branches doesn't look good :sweat_smile:

**Comment by MPParsley** [comment]
CodeClimate is no longer blocking PRs and is now based on the same sniffs as PHP codesniffer.
