### ISSUE TITLE
Providing settings under 'handler_settings' is deprecated

### ISSUE THREAD

**Issue by pfrenssen** [Gizra/og#519]
When running tests on Drupal 8.8 we are getting the following deprecation notice:

```
  15x: Providing settings under 'handler_settings' is deprecated and will be removed before 9.0.0. Move the settings in the root of the configuration array. See https://www.drupal.org/node/2870971.
    6x in SelectionHandlerTest::testSelectionHandlerResults from Drupal\Tests\og\Kernel\Entity
    4x in EntityCreateAccessTest::testViewPermissionDoesNotGrantCreateAccess from Drupal\Tests\og\Kernel\Entity
    3x in OgComplexWidgetTest::testFields from Drupal\Tests\og\Functional
    2x in SelectionHandlerTest::testSelectionHandler from Drupal\Tests\og\Kernel\Entity
```

Change record: [Entity reference selection handlers should extend a base class](https://www.drupal.org/node/2870971)

**Comment by pfrenssen** [comment]
We should aim to get this in the next alpha, so that OG is ready for Drupal 8.8 before it is released.

**Comment by pfrenssen** [comment]
This seems to be non-trivial. Our `OgSelection` handler can handle any kind of entity type, which is different than all other entity reference selection handlers which handle a single entity type.

We were using the `handler_settings` to facilitate this, but with the new change we need to do this with `SelectionPluginBase::setConfiguration()`.

**Comment by pfrenssen** [comment]
Unassigning again, I was hoping this to be a quick fix which I could do in my spare time today but I already ran out of time.

**Comment by claudiu-cristea** [comment]
I've added a new PR #577
