### ISSUE TITLE
Consider to unify permissions for managing roles and permissions in `administer permissions`

### ISSUE THREAD

**Issue by pfrenssen** [Gizra/og#526]
In Drupal 7 we had two separate permissions for managing roles and permissions: `manage roles` and `manage permissions`.

However these are very closely related since editing a role also allows the editing of the role's permissions, and a user with `manage permissions` can edit the permissions of all roles.

Both UIs are also very closely related, the role UI showing the permissions in a single column of checkboxes, while the permissions UI shows the same thing but in a matrix that covers all roles.

I would propose to do this in the same way as it is handled in Drupal core: with a single `administer permissions` permission that grants access to both.

**Comment by amitaibu** [comment]
> with a single administer permissions permission that grants access to both.

Agreed
