### ISSUE TITLE
No Query is Run in View When Using Group ID Contextual Filter for User with Multiple Group Memberships

### ISSUE THREAD

**Issue by fcbrooks** [Gizra/og#53]
Since 7.37 core update, if you have a view using the "OG Membership: Group ID" Contextual Filter set to provide "the OG groups of the logged in user" as a default when a filter is not provided, and "OG group" validation  is enabled along with "Allow multiple values", the query will not run for a user with multiple group memberships when no filter is provided, due to argument validation failing in og_plugin_argument_validate_group.inc.

This is due to the contract of entity_load being more strictly enforced starting in 7.37, in response to this issue, https://www.drupal.org/node/1003788.  The condition placed on the $ids parameter is 

"An array of entity IDs, or FALSE to load all entities."

The validate_argument function in og_plugin_argument_validate_group.inc calls entity_load_single with the string of concatenated gids that Views supports, ie. "1+2+3".  entity_load now tries to validate that this is numeric which fails, so no entities are returned, argument validation fails, and the query does not run.

I will be submitting a pull request with a proposed fix.

**Comment by fcbrooks** [comment]
Submitted pull request.

https://github.com/Gizra/og/pull/54

In full disclosure, the code in the patch was written by a colleague.  I am just handling the submission.

**Comment by amitaibu** [comment]
closing in favor of #54
