### ISSUE TITLE
8.x version of  og_get_groups_by_user()

### ISSUE THREAD

**Issue by meecect** [Gizra/og#535]
Would like to know how to do  og_get_groups_by_user() in the drupal 8.x branch.

Also would like to know in general where I can look in the code for similar utility functions.  For example, what is the easiest programmatic way to get a list of all groups?

thanks,

**Comment by pfrenssen** [comment]
> Would like to know how to do og_get_groups_by_user() in the drupal 8.x branch.

This is now handled by `MembershipManagerInterface::getUserGroups()`. Examples:

```
// Procedural code.
$groups = \Drupal::service('og.membership_manager')->getUserGroups($user);

// When using dependency injection, inject the membership manager, then call:
$groups = $this->membershipManager->getUserGroups($user);
```

> Also would like to know in general where I can look in the code for similar utility functions.

In Drupal 8 these utility functions are put in services. To see a list of the services that are available in OG, you can check `og.services.yml`. Here are some of the interesting ones:

* `OgAccess`: methods to check if a user has access to groups and group content.
* `OgGroupAudienceHelper`: to check if an entity is a group type, and to get the group audience fields.
* `GroupTypeManager`: methods related to managing groups: get a list of the bundles that are group types, add a group type, remove a group type etc.
* `MembershipManager`: a lot of stuff related to managing memberships. This is possibly the most important one for writing custom code that integrates with OG.
* `OgRoleManager`: methods related to roles.

> For example, what is the easiest programmatic way to get a list of all groups?

In Drupal 8 you can declare any content entity bundle as a group type, so you can use the entity API to get the list of entities that belong to a certain bundle. So for example if you create a node type and call it "group" and make it a group type in the UI, you can get a list of all these bundles by calling:

```
// Get a list of all nodes of the 'group' bundle.
$query = \Drupal::entityQuery('node');
$query->condition('bundle', 'group');
$group_ids = $query->execute();
```

If you need a list of all the group types that are defined you can call:

```
// Get an array of all group bundles, keyed by entity type.
$group_bundles = \Drupal::service('og.group_type_manager')->getAllGroupBundles();
```
