### ISSUE TITLE
Search API integration for OG-D8

### ISSUE THREAD

**Issue by damienmckenna** [Gizra/og#556]
Ensure that the group assignment for content can be indexed on Search API, and that this can then be used with Facet API as a facet.

**Comment by MPParsley** [comment]
When using #181, the audience field can be indexed as a simple entity reference field.

**Comment by damienmckenna** [comment]
Oh, nice! Thanks for the insights!

FYI I created PR #558 which updates Amitai's PR with the latest changes from the 8.x-1.x branch.

I'll follow up once I test out the changes.

**Comment by MPParsley** [comment]
@damienmckenna, let me know if this can be closed or if you think we need a custom processor.

**Comment by damienmckenna** [comment]
Yes, this works as-is, thanks for checking back.
