### ISSUE TITLE
Development roadmap for OG 8.x

### ISSUE THREAD

**Issue by andrewholgate** [Gizra/og#56]
Following on from a brief exchange with @amitaibu on Twitter.
# Rational

Porting over a module such as OG to Drupal 8 is a large, time consuming task. The current _guesstimate_ is around 100 developer days of work.
# Proposal

I'd like to propose that we come up with a development roadmap to bring the code to a stable `8.x-1.0` release.

I feel it would be beneficial to break the development of OG down into bite-sized milestones as it would likely encourage companies to sponsor at least some of the milestones in order to have the module stable for when Drupal 8 is released.
# Ideas

Rather than a fully featured Drupal 8 port of the Drupal 7 version, could a minimal viable product be a better target for the initial `8.x-1.0` release? Subsequent minor versions could then add these additional features (such as integration with other modules, etc)?

This could help get a minimal functioning version to the community earlier and spur on other developers / companies to add some of the missing features they need.
# Next Steps
1. Draft an initial roadmap - this will require someone with a good knowledge of the OG architecture.
2. Assign a very approximate number of developer days needed to complete each of the milestones.
3. Find sponsors and developers willing to offer time / money.

Thoughts?

**Comment by dpi** [comment]
I'd like to add that I've done a lot of work on Entity->Person in RNG ([GH](https://github.com/dpi/rng) / [D.O](https://www.drupal.org/project/rng)), an event management module. Although it doesn't apply directly, you may be able to take some hints from there. Ive also abstracted the Person into an "Identity" which can theoretically be any entity, but usually a Drupal User entity. I'm also really interested in integrating RNG with any work OG does for 8.x. Hit me up on IRC.

**Comment by amitaibu** [comment]
We are actively working on getting Gizra resources on this. We'll update as soon as it happens. no ETA yet.

**Comment by andrewholgate** [comment]
With Drupal 8 RC approaching, it'd be great to see a quick roadmap drafted so we can get a better idea of how this module can be divided up for development.

@amitaibu would you be able to give an ETA for just a draft roadmap?

**Comment by amitaibu** [comment]
Again, ETA's are hard at this point, but in terms of how we're going to tackle this:
1. Port OG audience fields (i.e. field API)
2. Port OG complex widget
3. Port EntityQuery (previously known as EFQ)
4. Port entity and specific node_access

Each item will be ported with its existing tests.

After those items, it will be much easier to delegate work to the community :)

**Comment by bunnyroo** [comment]
Is there an update on when the OG D8 release may be?  And is there anything I can do to assist?

**Comment by iBobik** [comment]
@bunnyroo It seems development happens [there](https://github.com/Gizra/og/tree/8.x-1.x). You probably can help with
updating README to be more intuitive.

Jan Pobořil

2016-02-16 18:44 GMT+01:00 bunnyroo notifications@github.com:

**Comment by amitaibu** [comment]
Development is back in this repo
