### ISSUE TITLE
og_role_grant() if role is already granted and user is not member

### ISSUE THREAD

**Issue by vpomey** [Gizra/og#57]
this provoqu

 Integrity constraint violation: 1062 Duplicate entry '694-3-4' for key 'PRIMARY'

suggested fix in og_role_grant : 

  // Get the existing user roles.
  $user_roles = og_get_user_roles($group_type, $gid, $uid, TRUE, FALSE);

thanks

**Comment by alesrebec** [comment]
Mirrored issue from drupal.org is here: https://www.drupal.org/node/2380967
@amitaibu can this one get some attention? It's probably there since og_get_user_roles() got the 5-th parameter ($check_active) which is TRUE by default.

**Comment by amitaibu** [comment]
https://www.drupal.org/node/2380967#comment-11686569
