### ISSUE TITLE
Schema error with og_complex widget settings

### ISSUE THREAD

**Issue by claudiu-cristea** [Gizra/og#574]
## Problem

With Drupal 8.8.x, the `EntityReferenceAutocompleteWidget` widget got a new setting, `match_limit`. But the `OgComplex` (which extends `EntityReferenceAutocompleteWidget`) settings schema (`field.widget.settings.og_complex`) has wrongly hardcopied the values from core instead of extending the core schema. This lead to a schema error with Drupal 8.8.x because `match_limit` setting has no schema.

## Proposal

Simply, make `field.widget.settings.og_complex` extend `field.widget.settings.entity_reference_autocomplete`. Remove the hard-coded schema.

**Comment by MPParsley** [comment]
Thanks!
Looks like the same copy paste had been done in #231.
