### ISSUE TITLE
Deprecate `Og::getSelectionHandler()`

### ISSUE THREAD

**Issue by pfrenssen** [Gizra/og#580]
The static function `Og::getSelectionHandler()` seems to be no longer needed and can be removed. The only thing that seems to make it different now from the standard implementation in `SelectionPluginManager::getSelectionHandler()` is that is allows to override the handler options, but it is only called once (in `og_entity_create_access()`) and here the `$options` are not even passed.

So we can remove this and call into the `SelectionPluginManager` instead.

It is possible that some of our users are still calling this in their custom code so we should handle this in two PRs: first deprecate it, and then in a later release it can be removed completely.

**Comment by MPParsley** [comment]
Fixed in https://github.com/Gizra/og/pull/610
