### ISSUE TITLE
Remove the match_limit schema when dropping support for 8.7.x

### ISSUE THREAD

**Issue by claudiu-cristea** [Gizra/og#581]
Remove the `match_limit` schema from `field.widget.settings.og_complex` when dropping support for Drupal 8.7.x.

**Comment by damienmckenna** [comment]
Won't this be solved when #160 is committed? Should we focus our attention there instead?

**Comment by MPParsley** [comment]
> Won't this be solved when #160 is committed? Should we focus our attention there instead?

@damienmckenna, I agree that 160 will be an important step forward for this project but the current PR's that try to solve that are in (very) a bad shape.

Have a look at https://github.com/Gizra/og/pull/570#pullrequestreview-307980013 I moved over the initial branch from amitaibu:160-remove-complex-widget to this repository so we can work on it more easily. I noticed you created a merge branch for different PR's, any chance you could have the work spent there flow back to #570?

**Comment by damienmckenna** [comment]
@MPParsley,
The PR I created (#571) was a stopgap I needed for a project to combine the three PRs so it could be added to a composer workflow.
I'll try to make time to work on #570 and the others to get them into a finished state that could be committed.

**Comment by claudiu-cristea** [comment]
> Won't this be solved when #160 is committed? Should we focus our attention there instead?

I have no idea. But if it does, it's still a question if it will be merged in time. That means before the support for Drupal 8.7.x is dropped. Then we can "won't fix" this. Otherwise this will get a simple cleanup PR.
