### ISSUE TITLE
Code guideline 

### ISSUE THREAD

**Issue by RoySegall** [Gizra/og#6]
OG have a lot of `og_` function that can move into the controller as static methods. For example `OG::IsGroup()` `OG:IsGroupContent()`. This also should effect the access part of OG(not og_access).

Any other thoughts?

**Comment by mglaman** [comment]
Yeah, I completely agree that there should be a static method that compliments D8 Entities. This can then also return actual entities (such as group memberships, group content, etc.)

**Comment by RoySegall** [comment]
But there could also be `OgAccess::CheckPermission()` or `OgAccess::GranPermission()` etc etc

**Comment by mglaman** [comment]
@RoySegall, would you like me to kick that off in my fork? Start working on some static helper classes for managing organic groups?

**Comment by RoySegall** [comment]
I think all those api function can move for now from the main module file. There are another issues but we can start by small steps.

**Comment by mradcliffe** [comment]
I agree with this approach.

**Comment by MPParsley** [comment]
There are still some utility classes but I suggest to use services for most of the group API.
