### ISSUE TITLE
Uninstalling 8.x leads to "Call to undefined function Exception()" WSOD

### ISSUE THREAD

**Issue by damienmckenna** [Gizra/og#600]
When you try to uninstall OG it says there are various config items that will also be deleted, when you confirm that request it results in the following error:
`Error: Call to undefined function Exception() in Drupal\og\Entity\OgMembershipType->delete() (line 103 of modules/contrib/og/src/Entity/OgMembershipType.php).`

The second time you trigger the uninstall process it just shows this item that is not removed:
> OG membership type
> * Default

This results in making it not fully possible to uninstall the module.

**Comment by pfrenssen** [comment]
This is strange, there is no call to `Exception()` in `Drupal\og\Entity\OgMembershipType`. The file also doesn't have a `delete()` method, and no line 103 where this call can be triggered, it is only 55 lines long.

Can you tell which branch you are using? Do you have the same problem when using the latest 8.x-1.x-dev version?

**Comment by damienmckenna** [comment]
It might be related to using #571, I'll have to dig into this later.

**Comment by damienmckenna** [comment]
This problem was caused by #231.
