### ISSUE TITLE
Error at admin/config/group/permissions/{entity_type}/{bundle} 

### ISSUE THREAD

**Issue by arifh** [Gizra/og#609]
\Drupal\og_ui\Form\OgPermissionsForm class not found .  where I get OgPermissionsForm . I checked OG module there is no OgPermissionsForm 

Please check : https://stackoverflow.com/questions/60058544/i-am-using-og-module-at-drupal-8-how-to-add-role-and-roles-permission-for-part

**Comment by MPParsley** [comment]
Group roles and permissions UI is still under development.

See https://github.com/Gizra/og/pull/243

**Comment by arifh** [comment]
when will you release it ??

**Comment by MPParsley** [comment]
It will be released in the beta version, when it's ready. You can [help getting this issue forward and  contributing](https://github.com/Gizra/og/wiki/Contributing) by testing it, providing feedback and writing tests.

Have a look at #240 for the roadmap.
