### ISSUE TITLE
Problem with  $membership->getRoles(); 

### ISSUE THREAD

**Issue by arifh** [Gizra/og#628]
$current_roles = $membership->getRoles(); retrieved roles of member . But the problem is when I manually update deleted field at og_membership__roles table , role array not change. After cache rebuild it is reflecting.  
I have another query how to unassigned role  ??

**Comment by arifh** [comment]
@MPParsley I am waiting for your response

**Comment by MPParsley** [comment]
@arifh, you should never interact directly with the Database.

Most API is available through services.
Have a look at this answer: https://github.com/Gizra/og/issues/535#issuecomment-513677322
