### ISSUE TITLE
How to display a user's groups using views ?

### ISSUE THREAD

**Issue by semiaddict** [Gizra/og#632]
I am trying to create an entity reference view to use for the og_audience reference field.
My aim is to filter the list of groups in the og_audience to only those the user is a member of, which I believe used to be the case in the D7 version.

I have tried using an og_membership view, a node view, and even a user view, but none seem to allow the creation of the desired relationships to achieve this.

It seems as if the group entity in the og_membership is not recognized as such in views, as I cannot create a relationship with a the group node from an og_membership.

How can I go by creating a view that lists a user's groups ?

**Comment by MPParsley** [comment]
@semiaddict, have a look at #254 and #565.

**Comment by semiaddict** [comment]
Great. Thank you @MPParsley.
