### ISSUE TITLE
How to set up Pathauto patterns in the Drupal 8 version?

### ISSUE THREAD

**Issue by jerrac** [Gizra/og#633]
How can I make pathauto generate url aliases like `/group/group-name/pages/page-title`?

This is the best attempt I could come up with based on the tokens pathauto's token browser listed as available:

`/group/[node:og_audience:0:entity]/pages/[node:title]`

When I regenerate the aliases, no article or basic page aliases are created. I have made both content types group content types, and I have created an article in my test group. 

Aliasing is working because my test group's alias is generated from this pattern: `/group/[node:title]`

I've search both here, and the Drupal issue queue for an answer. Everything I found seems to only apply to Drupal 7 versions of the modules... I need this on Drupal 8.

According to the readme, I should install the Entity API module and enable the entity-tokens module that comes with it. Unfortunately, it appears that the entity-tokens module is no longer present in the Drupal 8 version of Entity API. After installing Entity API, entity-tokens is not listed in my modules list, and when I check for it in my code, it doesn't exist. 

Are the tokens simply not available in the Drupal 8 version?

Thanks in advance.

Versions:
* Drupal 8.8.2
* OG 8.x-1.0-alpha4
* Entity 8.x-1.0
* Pathauto 8.x-1.6
* Token 8.x-1.6

**Comment by jerrac** [comment]
I revisited this today on a fresh instance of Drupal 8.8.5. I'm not sure what version of OG is being used, I ran composer update, so it should be the latest recommended version, or the latest dev. Oddly neither the module list in Drupal, nor drush pm-list show a version number....

Anyway, this seems to work just fine as a pattern for group content:

```
group/[node:og_audience:0]/[node:content-type]/[node:title]
```
Assuming you only need to worry about content being in a single group.

Annoyingly, non-group content will still end up under `/group/`. Like: `group/basic-page/about`.

The obvious fix for that is to just manually set the alias. But it would be nice if there was a way for pathauto to work differently on non-group content... 

I'd say that is it for this issue.

**Comment by MPParsley** [comment]
Another way would be to use node:menu-link:parents:join-path, it allows you to create menu subtrees:
 [node:og_audience:entity:title]/[node:menu-link:parents:join-path]/[node:title]

**Comment by jerrac** [comment]
Drupal says:

```
Path pattern is using the following invalid tokens: [node:og_audience:entity:title]. 
```
When I try: `[node:og_audience:entity:title]/[node:menu-link:parents:join-path]/[node:title]`.

![Screenshot_2020-04-14 Add Pathauto pattern grouptest](https://user-images.githubusercontent.com/910764/79279615-42744680-7e63-11ea-9ab4-9e665dd45a6c.png)

That's all I see for og_audience when using the token browser.

Wouldn't the `[node:menu-link:parents:join-path]` token require you give the content a menu link?

**Comment by MPParsley** [comment]
Indeed. But using menu links to map breadcrumbs / urls makes sense in our case.

**Comment by ceswebmaster** [comment]
I see this is closed but it's not working. I have the latest dev and you can't generate the pattern. Going to delete existing patterns it doesn't register any of the content related to and being the group. If you click to bulk generate the only thing updated is the 1 basic page node i have setup to act as the homepage. Any other content that is related to the group is not touched. I even went as simple as to only use [node:title] and still none of those nodes are touched.
