### ISSUE TITLE
Other groups field ignoring bundles settings

### ISSUE THREAD

**Issue by alfaguru** [Gizra/og#642]
To reproduce this error, configure more than one content type (CT1, CT2) to be a group. Add an audience field to another content type( CT3), and configure it so only CT1 is valid.

**Problem 1**. On editing a CT3 the "Other groups" field will return nodes of type CT2 as well as CT1. 

**Problem 2**. Attempting to submit with a CT2 node selected will cause an exception to be thrown as the validation of the "Other groups" field is incorrect in some way not yet identified.

I have a fix for problem 1 and will add a PR for it shortly.

**Comment by pfrenssen** [comment]
Fixed in #643
