### ISSUE TITLE
Difference between D7/D8 for group_content_access values

### ISSUE THREAD

**Issue by edvanleeuwen** [Gizra/og#644]
In D7 the values of group_content_access are:
```
0|Use group defaults
1|Public - accessible to all site users
2|Private - accessible only to group members
```

D8:
```
0|Public - accessible to all site users
1|Private - accessible only to group members
```

I do not know why this change has been done, but it affects a straight migration.

**Comment by MPParsley** [comment]
Hi @edvanleeuwen, thank you for your feedback.

In fact group access is a feature that is currently being ported in #242, I suggest you offer this feedback and discuss it over there.
