### ISSUE TITLE
Switch Travis CI integration to Github Apps

### ISSUE THREAD

**Issue by pfrenssen** [Gizra/og#651]
We are still using the legacy webhooks integration for Travis CI, but this is deprecated and is becoming unreliable. About half of the builds are not reporting back to Github at the moment and need to be rebuilt manually.

This can be solved by switching to the Github Apps integration of Travis CI, but this comes with some manual work:

* An account on travis.com is required (where previously the account on travis.org could be used).
* The Travis CI Github App must be enabled (follow instructions at https://travis-ci.com/account/repositories)
* The Travis CI integration for the OG repository must be migrated to Github Apps (follow instructions at https://travis-ci.com/account/migrate)

After this the builds should appear on the "Actions" tab for every PR, and the builds will run reliably again.

**Comment by pfrenssen** [comment]
@amitaibu is this something that you or your team can take care of?

**Comment by amitaibu** [comment]
@pfrenssen Sure. I'll ask @AronNovak to have a look when he gets some free time.

**Comment by AronNovak** [comment]
@amitaibu 
![image](https://user-images.githubusercontent.com/114076/86511387-e6cdaf80-bdf8-11ea-9b9f-7e31456c33c8.png)
May I have temporary admin permissions for this repo then?

**Comment by amitaibu** [comment]
@AronNovak Done

**Comment by AronNovak** [comment]
![image](https://user-images.githubusercontent.com/114076/86999226-615c4d80-c1b2-11ea-946a-e747bca1ed64.png)

**Comment by AronNovak** [comment]
![image](https://user-images.githubusercontent.com/114076/87004266-71c5f580-c1bd-11ea-8c96-fa7511d6b275.png)

**Comment by pfrenssen** [comment]
Isn't this fixed as part of #656? We are using Github apps now. Are there some tasks left to fulfill the scope of this ticket, or can it be closed?

**Comment by AronNovak** [comment]
@pfrenssen We completed this issue, indeed.
