### ISSUE TITLE
Do not fail 9.x.x builds on deprecation warnings

### ISSUE THREAD

**Issue by pfrenssen** [Gizra/og#663]
We have introduced a check for deprecation warnings in our CI pipelines when we were preparing the D9 compatibility. This is causing problems now that D9 is going full steam ahead and has started to deprecate things in preparation for Drupal 10.

Some of these deprecations cannot be resolved in a way that would work both on Drupal 8 and Drupal 9 (for example https://www.drupal.org/node/3154407 - this requires <code>symfony/event-dispatcher</code> version 4.x which is not compatible with Drupal 8).

There are two possibilities: either we start to maintain separate D8 and D9 versions, or we ignore the deprecation warnings for now on D9 builds). I would propose to do the latter.

**Comment by MPParsley** [comment]
Apart from the deprecation checking, aren't we bound to run into a situation where we need to break compatibility with Drupal 8?

**Comment by pfrenssen** [comment]
At the moment I don't think this will be necessary, unless if in the future we will start to depend on new features that are only available for D9.

I think this can happen quite organically. D8 is now feature frozen, only accepting bug fixes, and will be EOL in 16 months. There are definitely some very interesting feature additions planned for D9 which we might want to adopt (like [bundle classes](https://www.drupal.org/project/drupal/issues/2570593)) but realistically we are not moving fast, and those 16 months will pass quickly.

But yes, if we decide in the future that we will use D9 only features, then it will be a B/C break and we will have to make a new major release which is D9 only.
