### ISSUE TITLE
Function ReflectionType::__toString() is deprecated

### ISSUE THREAD

**Issue by MPParsley** [Gizra/og#667]
PHPUnit reports:

Unsilenced deprecation notices (10)
  10x: Function ReflectionType::__toString() is deprecated
    10x in GroupSubscribeFormatterTest::setUp from Drupal\Tests\og\Unit
 > Executing tests from /home/travis/build/Gizra/drupal/modules/og/og_ui/tests
PHPUnit 6.5.14 by Sebastian Bergmann and contributors.

Perhaps we should update phpunit according to https://www.drupal.org/node/3078763

**Comment by pfrenssen** [comment]
Fixed in #668.
