### ISSUE TITLE
Adopt strict typing

### ISSUE THREAD

**Issue by pfrenssen** [Gizra/og#679]
Now that we no longer support PHP 5 we can start using strict typing. This will help make our code more reliable since it will prevent us from doing any unwanted type casting.

In order to enforce this, we can require `slevomat/coding-standard` and add the following declaration to our `phpcs-ruleset.xml.dist`:

```
    <!-- Require the strict types declaration in every PHP file. -->
    <rule ref="SlevomatCodingStandard.TypeHints.DeclareStrictTypes">
        <properties>
            <property name="newlinesCountBetweenOpenTagAndDeclare" value="2"/>
        </properties>
    </rule>
```

**Comment by MPParsley** [comment]
Shouldn't this be added to https://www.drupal.org/project/issues/coder?
