### ISSUE TITLE
Groups audience required field cannot have single other group entry

### ISSUE THREAD

**Issue by edvanleeuwen** [Gizra/og#683]
If I set the groups audience field to be required, I have to enter a group in the primary field which is a selection of the groups I have joined. An admin should be able to enter a group in the other groups box.

**Comment by MPParsley** [comment]
Please not that the complex widget is to be removed and replaced by a simple entity reference field widget.

See WIP on #570

**Comment by edvanleeuwen** [comment]
Obsolete.
