### ISSUE TITLE
OgRole, OgRolePermission, OgUsersRole shouldn't be entities

### ISSUE THREAD

**Issue by amitaibu** [Gizra/og#70]
While I don't think there's a clear definition of when entity vs a "simple" DB record, I believe the above shouldn't be entities.

@RoySegall do you see any problem with this?

/cc @damiankloip

**Comment by RoySegall** [comment]
Well... Although we don't like to export them via code in Gizra, there are people that would like to export them as part of the deploy process. This can be managed through the new CMI in Drupal 8, If this is an entity we get for free api function for free(entity API) and users can be referenced to role using entity reference field.

**Comment by damiankloip** [comment]
Yes, agree. We get a lot of benefits from using entities. As Roy said, we can reference them easily. Otherwise we will need custom widgets and autocomplet behaviour.

People will also want to swap out the storage backends. Having entities is an abstraction that makes that really easy.

**Comment by amitaibu** [comment]
> Otherwise we will need custom widgets and autocomplet behaviour.

Those thingies are not exposed in the UI inside an entity - they have their custom form (very similar  to permissions/ role page in core)

So while I can be persuaded about exporting of OgRole (a role in an a group) OgRolePermission (The permissions that are allowed per role), but not about `OgUsersRole` -- which is simply a mapping of role ID and user ID. We definitely wouldn't want to export that.

**Comment by RoySegall** [comment]
Maybe `OgUsersRole` we don't want to export but we can't make it non entity, we skipping free api function and we can't use the query manager for this one.

**Comment by damiankloip** [comment]
Also for the storage backend plugability mentioned above. I think it makes sense for all to be entities too. If it causes problems we should reconsider. I think it will make much more simplicity in the long run.

**Comment by amitaibu** [comment]
I feel we're a bit abusing Entity here, but sure, let's re-address later if it's a problem.
