### ISSUE TITLE
OG Role is stepping on access handler's fields

### ISSUE THREAD

**Issue by idimopoulos** [Gizra/og#708]
This is just a suggestion. A role in OG groups is like having a role in the website but contained within a group.
In OG Role, the
```php
  /**
   * {@inheritdoc}
   */
  public function hasPermission($permission) {
    if ($this->isAdmin()) {
      return TRUE;
    }
    return in_array($permission, $this->permissions);
  }
```
seems to be taking it too far. The role should be more or less just a list of permissions and settings of a user. When asking if the user "has a permission" is like checking the list. The `if ($this->isAdmin())` is adding logic to this process and there is a whole process already behind this.
Access handler is already checking for the user being an admin and that **_is_** the place to put logic. The `::hasPermission()` should simply return whether a permission is included in the role permissions.

**Comment by idimopoulos** [comment]
Looking at the following, it seems that permissions don't matter if the OG role is flagged as admin. Is this the purpose of this flag? to create a UID1-like user role for the groups?
```php
/**
   * {@inheritdoc}
   */
  public function hasPermission($permission) {
    if ($this->isAdmin()) {
      return TRUE;
    }
    return in_array($permission, $this->permissions);
  }

  /**
   * {@inheritdoc}
   */
  public function grantPermission($permission) {
    if ($this->isAdmin()) {
      return $this;
    }
    if (!$this->hasPermission($permission)) {
      $this->permissions[] = $permission;
    }
    return $this;
  }

  /**
   * {@inheritdoc}
   */
  public function revokePermission($permission) {
    if ($this->isAdmin()) {
      return $this;
    }
    $this->permissions = array_diff($this->permissions, [$permission]);
    return $this;
  }
```

**Comment by pfrenssen** [comment]
Yes that is the way this is intended to work, and it was also like this in the D7 version of OG. A group admin is considered a super user and is automatically granted all permissions. It should typically only be granted to a technical user like the webmaster.

**Comment by idimopoulos** [comment]
Ook then, I guess this can be closed then :) Thanks.
