### ISSUE TITLE
Request subscription form allows user to choose admin role and active status

### ISSUE THREAD

**Issue by jerrac** [Gizra/og#718]
![image](https://user-images.githubusercontent.com/910764/108885152-4bbe5b80-75bc-11eb-86e5-7bb3aaa1aa31.png)
On my little test instance, a user requesting access to a public group can set their role, and their status. 

Drupal 8.9.13
OG 8.x-1.x-dev

I created a basic group content type, set basic page and article as group content, and enabled og_access.

I have 2 test users. I had one create a public group. Then I had the other go subscribe. I was presented with the options in the screenshot. If I check off "Administrator" and "Active", then hit the "Request membership" button, the user is subscribed to the group as an active administrator. It can edit or delete the group node.

No approval required from the actual owner.

I thought I had seen an issue about this, but I couldn't find it. 

I think my instance is generic enough that this should be recreate-able.

Edit:
Yes, my instance was pretty blank. I have a db dump with just the basics enabled that I restore to when I want to test something like this. The above behavior occurs exactly as described. All I did was create the group content type, enable og access on it, and give authenticated users permissions to manage their own group nodes.

My installed module list looks like:
![image](https://user-images.githubusercontent.com/910764/108887146-b40e3c80-75be-11eb-9d8e-a9e26c29a0a4.png)

**Comment by jerrac** [comment]
@MPParsley Since you seem the most active, I'll tag you. 

I was just poking around OG and ran into this issue again. Since it's been months, I thought tagging you might be a good idea. Apologies if it wasn't.

**Comment by MPParsley** [comment]
Hi @jerrac, thank you for reaching out.

I noticed you have "Organic Groups access control" enabled which is not yet part of the og module as it is being worked on in #242. Also #231 seems to be applied as it provides the functionality to add the user membership state. Do you have any other patches applied? If the issue only occurs with that PR patch enabled it would be best to further discuss this in #242 or more likely in #231.

**Comment by jerrac** [comment]
Oh for crying out loud... I thought I had switched fully back to stock OG 8.x1.8-dev. Instead I was still, somehow, on the fork I made and pulled several pull requests into. Including the access one.

Sorry about that.

I'll see if I can isolate which pull request this is showing up from, then comment there, or open a new issue.

**Comment by jerrac** [comment]
FYI, if there was something wrong in any of the pull requests I had merged into my branch, it's been fixed. I just redid everything based on the latest 8.x-1.x commits and I can't replicate it. Which is nice.

**Comment by MPParsley** [comment]
Glad to hear 👍
