### ISSUE TITLE
Merge problem with group content permissions

### ISSUE THREAD

**Issue by christianwiedemann** [Gizra/og#742]
` $permissions = $this->generateEntityOperationPermissionList($group_content_entity_type_id, $bundle_id); `  overwrite multiple event content permissions in getDefaultEntityOperationPermissions. Let's use array_merge instead.

**Comment by MPParsley** [comment]
Hi @christianwiedemann, could you clarify what the problem is here?
Before looping the bundles, the list is initialized as an empty array: $permissions = [];

**Comment by MPParsley** [comment]
Cf. https://github.com/Gizra/og/pull/748
