### ISSUE TITLE
Routing error when viewing Membership Types overview page

### ISSUE THREAD

**Issue by cofihouse** [Gizra/og#744]
I'm getting a WSOD post install when visiting the membership types administration page. Here's the error:

`Symfony\Component\Routing\Exception\MissingMandatoryParametersException: Some mandatory parameters are missing ("membership_type") to generate a URL for route "entity.og_membership_type.auto_label". in Drupal\Core\Routing\UrlGenerator->doGenerate() (line 181 of C:\wamp64\www\list\core\lib\Drupal\Core\Routing\UrlGenerator.php).`

I can visit the edit/add pages if I input the direct route.

**Comment by jludwig** [comment]
See: https://github.com/Gizra/og/pull/751

**Comment by cofihouse** [comment]
@jludwig pull request fixes my issue
