### ISSUE TITLE
og_users_roles migration is broken

### ISSUE THREAD

**Issue by alexhass** [Gizra/og#75]
I have tons of this error and ~90% of the items are not migrated:

```
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1-10-1' for key 'PRIMARY': INSERT INTO {og_users_roles} (uid, rid, gid, group_type) VALUES (:db_insert_placeholder_0, :db_insert_placeholder_1, :db_insert_placeholder_2, :db_insert_placeholder_3); Array ( [:db_insert_placeholder_0] => 1 [:db_insert_placeholder_1] => 10 [:db_insert_placeholder_2] => 1 [:db_insert_placeholder_3] => node ) (\includes\common.inc:7316)
```

**Comment by yamlfd** [comment]
I guess this comes from 3 entries in `og_users_roles_group` that have a gid = 0? It sounds like this are incorrect entries. I have no idea who they came into the system, but they exists in D6, too.

Should I just delete these 3 entries with gid = 0 or not?
