### ISSUE TITLE
How to make a view of a user's groups

### ISSUE THREAD

**Issue by cofihouse** [Gizra/og#752]
I have applied the PR from #565 and #352 but I still cannot figure out how to build a view that shows the groups to which a user is a member. The view should be displayed on a profile and visible to anyone who visits the profile.

I have spent HOURS trying numerous combinations with contextual filters and relationships, both from the previously mentioned PR. But I cannot get anything to work. Please help. This is very stressful and is absolutely key for the project I'm building.

**Comment by lozeone** [comment]
Im not sure if this is the best way to go about doing it, but I added this to the end of `og_views_data_alter()` in `og.views.inc`

It adds a views relationship for each entity type that you have enabled as an og group. For me this is almost always nodes.

So on a node view, you can add a relationship to a membership, then in contextual filters filter that membership by a specific user.  And you will get all group nodes a user is a member of.

Note: In views, the argument on the og_membership is confusingly named username, but its actually the user id.

<pre>
$groupTypeManager = \Drupal::service('og.group_type_manager');
  foreach(array_keys($groupTypeManager->getGroupMap()) as $entity_type_id){
    $data[$entity_type_id]['og_membership_group']['relationship'] = [
      'real field' => \Drupal::entityTypeManager()->getDefinition($entity_type_id)->getKey('id'),
      'base' => 'og_membership',
      'base field' => 'entity_id',
      'group' => new TranslatableMarkup('OG membership'),
      'label' => new TranslatableMarkup('OG Memberships'),
      'title' => new TranslatableMarkup('OG Memberships'),
      'id' => 'standard',
      'help' => new TranslatableMarkup('Reference the og_membership entities tied to this '. $entity_type_id . ' group.'),
      'join_extra' => [
        [
          // join on the entity type.
          'field' => 'entity_type',
          'value' => $entity_type_id,
        ],
      ],
    ];
  }
</pre>

**Comment by cofihouse** [comment]
Thank you so much! This finally works.
