### ISSUE TITLE
Sorting group membership field in account settings works when editing but not viewing

### ISSUE THREAD

**Issue by brightbold** [Gizra/og#87]
First reported in https://www.drupal.org/node/1567492#comment-7588005, I am having this same problem on my site. Steps to reproduce:
1. Go to Admin > Config > People > Account Settings > Manage Fields at: admin/config/people/accounts/fields
2. Click "edit" next to the "Group membership" field
3. Under Group membership field settings > Entity selection, change the following settings:
   - Sort by: "Don't sort" > "A field attached to this entity
   - Sort field: Title (column value), or choose another field of your choice
   - Sort direction: Ascending
4. Click "Save settings" button, clear cache and run cron
5. Edit a user account. The sort order will have changed. Now view the user account. Sort order remains in group ID order.

I've also tried this with "Sort by a property of the base table of the entity" and get the same results. (Although what I want is to use a custom field on the entity so I can control sort order manually.) It would be great if OG would respect the chosen sort order in both view and edit modes.

**Comment by amitaibu** [comment]
That issue is about 1.x version, which is no longer getting any attention. 

Is it on 2.x as well?

**Comment by amitaibu** [comment]
Actually, the sorting applies only to edit - that's how entity reference works.

**Comment by brightbold** [comment]
Yes, sorry - I'm on 7.x-2.7.

**Comment by brightbold** [comment]
Wait, really? Bummer. Hmm. I'll have to see if I can figure out how to sort them on the user account without breaking anything OG is doing — hopefully stackexchange will be my friend here. (If you have any tips for doing that I will happily accept them!)

**Comment by amitaibu** [comment]
A field formatter - my bet/ hope is that there's an existing one that does
it :)
