### ISSUE TITLE
Installing on a large web?

### ISSUE THREAD

**Issue by JacobCZ** [Gizra/og#92]
Hi, I'd like to ask you a bit tricky question. The thing is, I'm running a pretty large website (about 200k nodes and 2.5M comments) on drupal 7 and I would like to install OG there. 
Do you think it's a good idea? 
Could it break the structure somehow?
Can I install it on a subdomain (separate instance of drupal) and link it to the main instance?

(Due to the relatively massive size of the website, it's not really possible to create a development copy to test this... We can only test at a much smaller scale with a small portion of the original site's data)

Thanks in advance.

**Comment by amitaibu** [comment]
If your going for something like this, my best tip is try it on a dev site, no matter how big you live is. Normally it shouldn't be a problem, but I have no clue what kind of site you have. Good luck ;)
